version: '3.4'

services:
  posterr.test:
    depends_on: [database]
    image: ${DOCKER_REGISTRY-}posterrtests
    build:
      context: .
      dockerfile: test/Posterr.Data.Tests/Dockerfile
    networks:
      - appnetwork
    environment:
      CONNECTIONSTRINGS__DBCONNECTION: ${CONNECTIONSTRINGS__DBCONNECTION}
  database:
    image: postgres:14.2-alpine
    container_name: posterr_test_database
    restart: always
    ports:
      - 5432:5432   
    networks:
      - appnetwork
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./docker/postgresql/db-data/:/var/lib/postgresql/data/
      - ./docker/postgresql/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
networks:
  appnetwork: